name: Deployment pipeline

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Render Deploy Action
        run: curl https://api.render.com/deploy/srv-cheqqvm4dad1jqfnn950?key=G9j99Lq1Aew
